"""High-level reciprocal-spectrum sampling, expansion, and numerical tools."""

from .domains import (
    EvanescentDisk,
    IntersectionDomain,
    KDomain,
    PolygonKDomain,
    PropagationDisk,
    PupilDomain,
    brillouin_zone_domain,
    irreducible_zone_domain,
)
from .integration import (
    IntegrationMeasure,
    JacobianMeasure,
    NormalizedAreaMeasure,
    SolidAngleMeasure,
    TransverseWavevectorMeasure,
    integrate,
    integrate_field,
)
from .interpolation import InterpolationResult, interpolate
from .model import (
    CartesianGrid,
    FieldSamples,
    KSampling,
    MaxSpacing,
    PointCounts,
    PolarGrid,
    SamplingConstraint,
    SourceRegion,
    TargetRegion,
    ValueRepresentation,
)
from .periodic import (
    ExpansionGenerator,
    ExpansionMap,
    PeriodicKSpace,
    PeriodicSamplingPlan,
    build_expansion_map,
    make_periodic_plan,
)
from .representations import (
    AxialVectorRepresentation,
    ComplexScalarRepresentation,
    FourierOrderTranslation,
    IdentityTranslation,
    PolarVectorRepresentation,
    RejectTranslations,
    SPPolarizationRepresentation,
    ScalarRepresentation,
    TensorRepresentation,
    TranslationAction,
)
from .sampling import NonPeriodicSampler

__all__ = [
    "AxialVectorRepresentation",
    "CartesianGrid",
    "ComplexScalarRepresentation",
    "EvanescentDisk",
    "ExpansionGenerator",
    "ExpansionMap",
    "FieldSamples",
    "FourierOrderTranslation",
    "IdentityTranslation",
    "IntegrationMeasure",
    "InterpolationResult",
    "IntersectionDomain",
    "JacobianMeasure",
    "KDomain",
    "KSampling",
    "MaxSpacing",
    "NonPeriodicSampler",
    "NormalizedAreaMeasure",
    "PeriodicKSpace",
    "PeriodicSamplingPlan",
    "PointCounts",
    "PolarGrid",
    "PolarVectorRepresentation",
    "PolygonKDomain",
    "PropagationDisk",
    "PupilDomain",
    "RejectTranslations",
    "SPPolarizationRepresentation",
    "SamplingConstraint",
    "ScalarRepresentation",
    "SolidAngleMeasure",
    "SourceRegion",
    "TargetRegion",
    "TensorRepresentation",
    "TranslationAction",
    "TransverseWavevectorMeasure",
    "ValueRepresentation",
    "brillouin_zone_domain",
    "build_expansion_map",
    "integrate",
    "integrate_field",
    "interpolate",
    "irreducible_zone_domain",
    "make_periodic_plan",
]
