from typing import Protocol

import numpy as np
from numpy.typing import ArrayLike, NDArray

from reciprocal.cells.model import PolygonDomain

BoolArray = NDArray[np.bool_]

class KDomain(Protocol):
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class PropagationDisk:
    radius: float
    center: tuple[float, float]
    def __init__(self, radius: float, center: tuple[float, float] = ...) -> None: ...
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class EvanescentDisk:
    propagating_radius: float
    max_parallel_wavevector: float
    center: tuple[float, float]
    def __init__(self, propagating_radius: float, max_parallel_wavevector: float, center: tuple[float, float] = ...) -> None: ...
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def is_evanescent(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class PupilDomain:
    outer_radius: float
    inner_radius: float
    center: tuple[float, float]
    def __init__(self, outer_radius: float, inner_radius: float = ..., center: tuple[float, float] = ...) -> None: ...
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class PolygonKDomain:
    polygon: PolygonDomain
    def __init__(self, polygon: PolygonDomain) -> None: ...
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class IntersectionDomain:
    domains: tuple[KDomain, ...]
    def __init__(self, domains: tuple[KDomain, ...]) -> None: ...
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> BoolArray: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

def intersection_area(domain: KDomain, polygon: PolygonDomain) -> float: ...
def brillouin_zone_domain(zone: object) -> PolygonKDomain: ...
def irreducible_zone_domain(zone: object) -> PolygonKDomain: ...
