from collections.abc import Mapping
from typing import Any

import numpy as np
from matplotlib.artist import Artist
from matplotlib.axes import Axes
from matplotlib.collections import PathCollection, PolyCollection
from matplotlib.figure import Figure
from matplotlib.patches import Circle, Polygon, Wedge
from numpy.typing import ArrayLike, NDArray

from .brillouin_zone import BrillouinZone
from .band_path import HighSymmetryPath
from .cells.model import PolygonDomain, UnitCell
from .kspace import KSpace
from .kvector import KVectorGroup
from .lattice import Lattice, LatticeVectors
from .spectrum.domains import KDomain
from .spectrum.interpolation import InterpolationResult
from .spectrum.model import FieldSamples, KSampling
from .spectrum.periodic import ExpansionMap, PeriodicKSpace, PeriodicSamplingPlan

def choose_color(item: int, n_items: int) -> NDArray[np.float64]: ...

class Canvas:
    fig: Figure
    ax: Axes
    bbox: list[list[float]]
    colors: dict[str, object]
    def __init__(self, ax: Axes | None = ...) -> None: ...
    def make_colors(self) -> None: ...
    def update_bbox(self, box: ArrayLike) -> None: ...
    def plot_vectors(self, plot_obj: Lattice | LatticeVectors) -> tuple[Artist, ...]: ...
    def plot_bzone(self, plot_obj: Lattice | BrillouinZone | PeriodicKSpace | PeriodicSamplingPlan, **kwargs: Any) -> Polygon: ...
    def plot_ibzone(self, plot_obj: Lattice | BrillouinZone | PeriodicKSpace | PeriodicSamplingPlan, **kwargs: Any) -> Polygon: ...
    def plot_special_points(self, plot_obj: object, **kwargs: Any) -> tuple[Circle, ...]: ...
    def plot_irreducible_uc(self, plot_obj: object, **kwargs: Any) -> Polygon: ...
    def plot_unit_cell(self, plot_obj: Lattice | UnitCell | BrillouinZone | PeriodicKSpace | PeriodicSamplingPlan, **kwargs: Any) -> Polygon: ...
    def plot_lattice(self, lattice: Lattice, orders: ArrayLike | None = ..., label_orders: bool = ..., **kwargs: Any) -> tuple[Artist, tuple[Artist, ...]]: ...
    def plot_tessellation(self, lattice: Lattice, orders: ArrayLike | None = ..., label_orders: bool = ..., **kwargs: Any) -> tuple[Artist, tuple[Artist, ...]]: ...
    def plot_tesselation(self, lattice: Lattice, orders: ArrayLike | None = ..., label_orders: bool = ..., **kwargs: Any) -> tuple[Artist, tuple[Artist, ...]]: ...
    def plot_lattice_distance_groups(self, lattice: Lattice, max_order: int = ..., label_orders: bool = ...) -> tuple[Artist, ...]: ...
    def plot_sampling(self, sampling: object, color: object | None = ...) -> object: ...
    def plot_order(self, pos: ArrayLike, order1: int, order2: int) -> Artist: ...
    def plot_domain(self, domain: KDomain | PolygonDomain | UnitCell, **kwargs: Any) -> tuple[Artist, ...]: ...
    def plot_spectrum(self, value: KSpace | KSampling | FieldSamples[Any] | PeriodicSamplingPlan | ExpansionMap | KDomain, **kwargs: Any) -> tuple[Artist, ...]: ...
    def plot_fermi_circle(self, kspace: KSpace | KDomain | float, linewidth: float = ..., color: object = ..., fill: bool = ..., **kwargs: Any) -> Circle: ...
    def plot_symmetry_cone(self, value: KSpace | Lattice | BrillouinZone | PeriodicKSpace | PeriodicSamplingPlan, color: object = ..., start_angle: float = ...) -> Polygon | Wedge: ...
    def plot_bloch_families(self, bloch_families: Mapping[Any, object] | ExpansionMap | PeriodicSamplingPlan, plot_n_families: int | str = ..., legend: bool = ...) -> tuple[PathCollection, ...]: ...
    def plot_point_sampling(self, points: ArrayLike | KVectorGroup | KSampling | FieldSamples[Any] | PeriodicSamplingPlan | ExpansionMap, plot_n_points: int | str = ..., color: object = ..., marker: str = ..., label: str = ..., **kwargs: Any) -> PathCollection: ...
    def plot_point_sampling_weighted(self, points: ArrayLike | KVectorGroup | KSampling | FieldSamples[Any] | PeriodicSamplingPlan | ExpansionMap, weighting: ArrayLike | None = ..., plot_n_points: int | str = ..., marker: str = ..., label: str = ..., *, physical: bool = ..., **kwargs: Any) -> PathCollection: ...
    def plot_field(self, field: FieldSamples[Any], *, component: int | tuple[int, ...] | None = ..., magnitude: bool = ..., **kwargs: Any) -> PathCollection: ...
    def plot_interpolation(self, kpoints: ArrayLike | KVectorGroup | FieldSamples[Any] | InterpolationResult, values: ArrayLike | None = ..., **kwargs: Any) -> PolyCollection: ...
    def plot_high_symmetry_path(self, path: HighSymmetryPath, **kwargs: Any) -> tuple[tuple[Artist, ...], PathCollection, tuple[Artist, ...]]: ...
