from typing import Any

from matplotlib.axes import Axes
from matplotlib.collections import PathCollection, PolyCollection
from matplotlib.figure import Figure
from numpy.typing import ArrayLike

from .kspace import KSpace
from .kvector import KVectorGroup

class Canvas:
    fig: Figure
    ax: Axes
    def __init__(self, ax: Axes | None = ...) -> None: ...
    def plot_vectors(self, plot_obj: object) -> None: ...
    def plot_bzone(self, plot_obj: object) -> None: ...
    def plot_special_points(self, plot_obj: object) -> None: ...
    def plot_ibzone(self, plot_obj: object) -> None: ...
    def plot_irreducible_uc(self, plot_obj: object) -> None: ...
    def plot_unit_cell(self, plot_obj: object) -> None: ...
    def plot_lattice(self, lattice: object, orders: ArrayLike | None = ..., label_orders: bool = ...) -> None: ...
    def plot_tessellation(self, lattice: object, orders: ArrayLike | None = ..., label_orders: bool = ..., **kwargs: Any) -> None: ...
    def plot_tesselation(self, lattice: object, orders: ArrayLike | None = ..., label_orders: bool = ..., **kwargs: Any) -> None: ...
    def plot_sampling(self, sampling: object, color: object | None = ...) -> None: ...
    def plot_fermi_circle(self, kspace: KSpace | float, linewidth: float = ..., color: object = ..., fill: bool = ..., **kwargs: Any) -> None: ...
    def plot_symmetry_cone(self, kspace: KSpace, color: object = ..., start_angle: float = ...) -> None: ...
    def plot_point_sampling(self, points: ArrayLike | KVectorGroup, plot_n_points: int | str = ..., color: object = ..., marker: str = ..., label: str = ...) -> PathCollection: ...
    def plot_point_sampling_weighted(self, points: ArrayLike | KVectorGroup, weighting: ArrayLike, plot_n_points: int | str = ..., marker: str = ..., label: str = ...) -> PathCollection: ...
    def plot_interpolation(self, kpoints: KVectorGroup, values: ArrayLike) -> PolyCollection: ...
