from typing import Literal

import numpy as np
from numpy.typing import ArrayLike, NDArray

FloatArray = NDArray[np.float64]

class KVector:
    wavelength: float
    k0: float
    n: float
    theta: float
    phi: float
    kx: float
    ky: float
    kz: float
    weighting: float | None
    def __init__(self, wavelength: float, n: float | None = ..., theta: float | None = ..., phi: float | None = ..., normal: float | None = ..., kx: float | None = ..., ky: float | None = ..., kz: float | None = ..., weighting: float | None = ..., validate: bool = ...) -> None: ...
    def validate_data(self) -> int: ...
    def complete_data(self, combination: int) -> None: ...
    def get_n_from_k(self) -> float: ...
    def get_normal_from_k(self) -> float: ...
    def get_kz_from_kxy_n_normal(self) -> float: ...
    def get_theta_phi_from_k(self) -> list[float]: ...
    def get_k_from_theta_phi_n_normal(self) -> list[float]: ...
    def validateData(self) -> int: ...
    def completeData(self, combination: int) -> None: ...
    def getNFromK(self) -> float: ...
    def getNormalFromK(self) -> float: ...
    def getKZFromKXYNNormal(self) -> float: ...
    def getThetaPhiFromK(self) -> list[float]: ...
    def getKFromThetaPhiNNormal(self) -> list[float]: ...
    @property
    def knorm(self) -> float: ...
    @property
    def k(self) -> FloatArray: ...
    @property
    def normal(self) -> Literal["+z", "-z"]: ...

class KVectorGroup:
    wavelength: float
    k0: float
    n_rows: int
    data_: FloatArray
    def __init__(self, wavelength: float, n_rows: int, n: ArrayLike | None = ..., theta: ArrayLike | None = ..., phi: ArrayLike | None = ..., normal: ArrayLike | None = ..., kx: ArrayLike | None = ..., ky: ArrayLike | None = ..., kz: ArrayLike | None = ..., validate: bool = ..., data: ArrayLike | None = ..., weighting: ArrayLike | None = ...) -> None: ...
    def validate_data(self) -> int: ...
    def complete_data(self, combination: int) -> None: ...
    def get_n_from_k(self) -> FloatArray: ...
    def get_normal_from_k(self) -> FloatArray: ...
    def get_kz_from_kxy_n_normal(self) -> FloatArray: ...
    def get_theta_phi_from_k(self) -> list[FloatArray]: ...
    def get_k_from_theta_phi_n_normal(self) -> list[FloatArray]: ...
    def validateData(self) -> int: ...
    def completeData(self, combination: int) -> None: ...
    def getNFromK(self) -> FloatArray: ...
    def getNormalFromK(self) -> FloatArray: ...
    def getKZFromKXYNNormal(self) -> FloatArray: ...
    def getThetaPhiFromK(self) -> list[FloatArray]: ...
    def getKFromThetaPhiNNormal(self) -> list[FloatArray]: ...
    @property
    def knorm(self) -> FloatArray: ...
    @property
    def k(self) -> FloatArray: ...
    @property
    def kx(self) -> FloatArray: ...
    @property
    def ky(self) -> FloatArray: ...
    @property
    def kz(self) -> FloatArray: ...
    @property
    def theta(self) -> FloatArray: ...
    @property
    def phi(self) -> FloatArray: ...
    @property
    def normal_(self) -> FloatArray: ...
    @property
    def normal(self) -> NDArray[np.str_]: ...
    @property
    def n(self) -> FloatArray: ...
    @property
    def weighting(self) -> FloatArray: ...
    def sort(self, column: str, order: str = ...) -> None: ...
    def slice(self, row: int) -> KVector: ...
    def __add__(self, other: KVectorGroup) -> KVectorGroup: ...

class BlochFamily(KVectorGroup):
    @property
    def order1(self) -> FloatArray: ...
    @property
    def order2(self) -> FloatArray: ...
