from enum import Enum
from typing import Literal

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .bravais import BravaisLattice
from .brillouin_zone import BrillouinZone
from .cells.model import UnitCell as ImmutableUnitCell
from .numerics import Tolerances
from .unit_cell import UnitCell

FloatArray = NDArray[np.float64]
IntArray = NDArray[np.int64]

class LatticeType(str, Enum):
    REAL_SPACE: LatticeType
    RECIPROCAL: LatticeType

def unit_vector(vector: ArrayLike) -> FloatArray: ...
def angle_between(first: ArrayLike, second: ArrayLike) -> float: ...
def make_vectors(length1: float, length2: float, angle: float) -> tuple[FloatArray, FloatArray]: ...

class LatticeVectors:
    @property
    def basis(self) -> FloatArray: ...
    @property
    def vec1(self) -> FloatArray: ...
    @property
    def vec2(self) -> FloatArray: ...
    @property
    def length1(self) -> float: ...
    @property
    def length2(self) -> float: ...
    @property
    def lengths(self) -> FloatArray: ...
    @property
    def angle(self) -> float: ...
    @property
    def signed_area(self) -> float: ...
    @property
    def area(self) -> float: ...
    @property
    def gram_matrix(self) -> FloatArray: ...
    def __init__(self, vector1: ArrayLike, vector2: ArrayLike) -> None: ...
    @classmethod
    def from_vectors(cls, vector1: ArrayLike, vector2: ArrayLike) -> LatticeVectors: ...
    @classmethod
    def from_lengths_angle(cls, length1: float, length2: float, angle: float) -> LatticeVectors: ...
    def reciprocal_vectors(self) -> LatticeVectors: ...
    def get_shortest_vectors(self) -> tuple[FloatArray, FloatArray]: ...

def classify_bravais(
    vectors: LatticeVectors, tolerances: Tolerances | None = ...
) -> BravaisLattice: ...

class Lattice:
    @property
    def lattice_type(self) -> Literal["real_space", "reciprocal"]: ...
    @property
    def vectors(self) -> LatticeVectors: ...
    @property
    def bravais(self) -> BravaisLattice: ...
    @property
    def unit_cell(self) -> UnitCell: ...
    @property
    def primitive_cell(self) -> ImmutableUnitCell: ...
    @property
    def conventional_cell(self) -> ImmutableUnitCell: ...
    @property
    def brillouin_zone(self) -> BrillouinZone: ...
    def __init__(
        self,
        lattice_vectors: LatticeVectors,
        lattice_type: Literal["real_space", "reciprocal"] | LatticeType = ...,
    ) -> None: ...
    @classmethod
    def from_vectors(
        cls,
        vector1: ArrayLike,
        vector2: ArrayLike,
        *,
        lattice_type: Literal["real_space", "reciprocal"] | LatticeType = ...,
    ) -> Lattice: ...
    @classmethod
    def from_lengths_angle(
        cls,
        length1: float,
        length2: float,
        angle: float,
        *,
        lattice_type: Literal["real_space", "reciprocal"] | LatticeType = ...,
    ) -> Lattice: ...
    @classmethod
    def from_lat_vec_args(cls, **kwargs: object) -> Lattice: ...
    def make_reciprocal(self) -> Lattice: ...
    def determine_bravais_lattice(self, tolerances: Tolerances | None = ...) -> BravaisLattice: ...
    def enumerate_orders(self, max_coefficient: int) -> tuple[IntArray, FloatArray]: ...
    def orders_by_distance(
        self, max_order: int, tolerances: Tolerances | None = ...
    ) -> tuple[list[IntArray], FloatArray]: ...
    def translation_shells(
        self, number_of_shells: int, tolerances: Tolerances | None = ...
    ) -> tuple[list[IntArray], FloatArray]: ...
