from typing import Any, Mapping, Protocol

from numpy.typing import ArrayLike, NDArray

class SamplingDomain(Protocol):
    @property
    def area(self) -> float: ...
    def contains(self, points: ArrayLike) -> NDArray[Any]: ...
    def bounds(self) -> tuple[float, float, float, float]: ...

class PointCounts:
    first: int
    second: int
    def __init__(self, first: int, second: int | None = ...) -> None: ...
    def as_legacy(self) -> Mapping[str, object]: ...

class MaxSpacing:
    value: float
    def __init__(self, value: float) -> None: ...
    def as_legacy(self) -> Mapping[str, object]: ...

SamplingConstraint = PointCounts | MaxSpacing | Mapping[str, object] | None
def legacy_constraint(constraint: SamplingConstraint) -> Mapping[str, object] | None: ...

class SamplingResult:
    points: NDArray[Any]
    normalized_weights: NDArray[Any]
    integration_element: float
    domain: SamplingDomain
    point_ids: NDArray[Any]
    kz: NDArray[Any] | None
    metadata: Mapping[str, object]
    def __init__(self, points: ArrayLike, normalized_weights: ArrayLike, integration_element: float, domain: SamplingDomain, point_ids: ArrayLike | None = ..., kz: ArrayLike | None = ..., metadata: Mapping[str, object] = ...) -> None: ...
    @property
    def weights(self) -> NDArray[Any]: ...
    @property
    def physical_weights(self) -> NDArray[Any]: ...
    @property
    def symmetry_operations(self) -> tuple[object, ...] | None: ...
    def integrate(self, values: ArrayLike, *, valid: ArrayLike | None = ...) -> NDArray[Any]: ...
    def average(self, values: ArrayLike, *, valid: ArrayLike | None = ...) -> NDArray[Any]: ...
    def with_kz(self, magnitude: float, direction: int = ...) -> SamplingResult: ...
    def to_kvectors(self, wavelength: float, refractive_index: float, direction: int = ...) -> Any: ...
