from enum import Enum
from typing import Any

from .bravais import BravaisLattice

import numpy as np
from numpy.typing import ArrayLike, NDArray

FloatArray = NDArray[np.float64]
IntArray = NDArray[np.int64]

class PointOperation:
    fractional: IntArray
    cartesian: FloatArray
    def __init__(self, fractional: ArrayLike, cartesian: ArrayLike) -> None: ...
    @property
    def determinant(self) -> int: ...
    def apply(self, points: ArrayLike) -> FloatArray: ...

class PointGroup:
    operations: tuple[PointOperation, ...]
    name: str
    def __init__(self, operations: tuple[PointOperation, ...], name: str) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PointOperation: ...

class OrbitMember:
    point: FloatArray
    generating_operations: tuple[PointOperation, ...]
    def __init__(self, point: ArrayLike, generating_operations: tuple[PointOperation, ...]) -> None: ...

class PointOrbit:
    representative: FloatArray
    reciprocal_basis: FloatArray
    point_group: PointGroup
    members: tuple[OrbitMember, ...]
    def __init__(self, representative: ArrayLike, reciprocal_basis: ArrayLike, point_group: PointGroup, members: tuple[OrbitMember, ...]) -> None: ...
    @property
    def points(self) -> FloatArray: ...

def point_group(reciprocal_basis: ArrayLike, bravais: BravaisLattice, *, tolerance: float = ...) -> PointGroup: ...
def equivalent_mod_lattice(first: ArrayLike, second: ArrayLike, reciprocal_basis: ArrayLike, *, tolerance: float = ...) -> bool: ...
def little_group(point: ArrayLike, reciprocal_basis: ArrayLike, operations: PointGroup | tuple[PointOperation, ...], *, tolerance: float = ...) -> tuple[PointOperation, ...]: ...
def point_orbit(point: ArrayLike, reciprocal_basis: ArrayLike, operations: PointGroup | tuple[PointOperation, ...], *, tolerance: float = ...) -> tuple[FloatArray, ...]: ...
def point_orbit_with_operations(point: ArrayLike, reciprocal_basis: ArrayLike, operations: PointGroup | tuple[PointOperation, ...], *, tolerance: float = ...) -> PointOrbit: ...

class SpecialPoint(Enum): ...
class PointSymmetry(Enum): ...

class Symmetry:
    group: PointSymmetry
    def __init__(self, symmetry: PointSymmetry) -> None: ...
    @classmethod
    def from_string(cls, string: str) -> Symmetry | SymmetryCombination: ...
    def get_n_symmetry_ops(self) -> int: ...
    def get_symmetry_cone_angle(self) -> float: ...
    def apply_symmetry_operators(self, points: ArrayLike, values: ArrayLike | None = ...) -> FloatArray | tuple[FloatArray, FloatArray]: ...
    def compatible(self, other: Any) -> bool: ...

class SymmetryCombination:
    stack: list[Symmetry]
    def __init__(self, symmetries: list[Symmetry | PointSymmetry]) -> None: ...
    def get_n_symmetry_ops(self) -> int: ...
    def get_symmetry_cone_angle(self) -> float: ...
    def apply_symmetry_operators(self, points: ArrayLike, values: ArrayLike | None = ...) -> FloatArray | tuple[FloatArray, FloatArray]: ...
    def compatible(self, other: Any) -> bool: ...
