from enum import Enum
from typing import Any

import numpy as np
from numpy.typing import ArrayLike, NDArray

FloatArray = NDArray[np.float64]

class SpecialPoint(Enum): ...
class PointSymmetry(Enum): ...

class Symmetry:
    group: PointSymmetry
    def __init__(self, symmetry: PointSymmetry) -> None: ...
    @classmethod
    def from_string(cls, string: str) -> Symmetry | SymmetryCombination: ...
    def get_n_symmetry_ops(self) -> int: ...
    def get_symmetry_cone_angle(self) -> float: ...
    def apply_symmetry_operators(self, points: ArrayLike, values: ArrayLike | None = ...) -> FloatArray | tuple[FloatArray, FloatArray]: ...
    def compatible(self, other: Any) -> bool: ...

class SymmetryCombination:
    stack: list[Symmetry]
    def __init__(self, symmetries: list[Symmetry | PointSymmetry]) -> None: ...
    def get_n_symmetry_ops(self) -> int: ...
    def get_symmetry_cone_angle(self) -> float: ...
    def apply_symmetry_operators(self, points: ArrayLike, values: ArrayLike | None = ...) -> FloatArray | tuple[FloatArray, FloatArray]: ...
    def compatible(self, other: Any) -> bool: ...
