from typing import Any
import numpy as np
from numpy.typing import ArrayLike, NDArray
from .symmetry import Symmetry, SymmetryCombination

FloatArray = NDArray[np.float64]

class UnitCell:
    lattice: Any
    vertices: FloatArray
    irreducible: FloatArray
    max_extent: float
    def __init__(self, lattice: Any, WignerSeitz: bool = ...) -> None: ...
    def area(self) -> float: ...
    def crop_to_bz(self, points: ArrayLike, return_indices: bool = ...) -> FloatArray | tuple[FloatArray, NDArray[Any]]: ...
    def crop_to_ibz(self, points: ArrayLike, return_indices: bool = ..., tol: float = ...) -> FloatArray | tuple[FloatArray, NDArray[Any]]: ...
    def sample(self, constraint: dict[str, object] | None = ..., center: ArrayLike = ..., use_symmetry: bool = ...) -> tuple[FloatArray, FloatArray]: ...
    def integration_element(self, constraint: dict[str, object]) -> float: ...
    def symmetry(self) -> Symmetry | SymmetryCombination: ...
